/*
 * Main Question UI
 * Parsons Problems V0.3
 */
package parsonsproblems;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;


/**
 * @author UP815458
 */
public class ParsonsProblemsQUI extends javax.swing.JFrame {
    static int qNo;
    static String[] qTextArray;
    static String[][] trueAnswers;
    static String[][] falseAnswers;
    static int[] marks;
    static boolean[] completedQs;
    static int[] currentPoints;
    boolean isCorrect = false;
    /**
     * Initialises the components and sets up the question
     * @param qNumber
     * @param qTxtList
     * @param inMarks
     * @param trueAnswerList
     * @param falseAnswerList
     * @param completedQuestions
     */
    public ParsonsProblemsQUI(int qNumber, String[] qTxtList, int[] inMarks, String[][] trueAnswerList, String[][] falseAnswerList, boolean[] completedQuestions, int[] inCurrentPoints) {
        qNo = qNumber;
        qTextArray = qTxtList;
        marks = inMarks;
        trueAnswers = trueAnswerList;
        falseAnswers = falseAnswerList;
        completedQs = completedQuestions;
        if(completedQs[qNo-1] == true){
            isCorrect = true;
        }
        currentPoints = inCurrentPoints;
        initAnswers();
        initComponents();
        initQuestionDetails();
        setTextFields();
        //remove the "previous" button on question 1
        if(qNo == 1){
            previousButton.setVisible(false);
        }
        if(qNo == 10){
            nextButton.setText("Finish");
        }
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionInfoPanel = new javax.swing.JPanel();
        QNoDisp = new javax.swing.JLabel();
        QTextDisp = new javax.swing.JLabel();
        MarkingPanel = new javax.swing.JPanel();
        marksLabel = new javax.swing.JLabel();
        marksScore = new javax.swing.JLabel();
        increaseMarkDisp = new javax.swing.JLabel();
        totalMarksScore = new javax.swing.JLabel();
        totalMarksLabel = new javax.swing.JLabel();
        navPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        AnswerPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        submitAnswerButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        answerBlock = new javax.swing.JPanel();
        answerPosTopPanel = new javax.swing.JPanel();
        posOneText = new javax.swing.JLabel();
        answer1TextAndButtonBlock = new javax.swing.JPanel();
        moveOneDownPos1 = new javax.swing.JButton();
        answerPos2Panel = new javax.swing.JPanel();
        posTwoText = new javax.swing.JLabel();
        buttonPanelPosTwo = new javax.swing.JPanel();
        moveOneUpPos2 = new javax.swing.JButton();
        moveOneDownPos2 = new javax.swing.JButton();
        answerPos3Panel = new javax.swing.JPanel();
        posThreeText = new javax.swing.JLabel();
        buttonPanelPosThree = new javax.swing.JPanel();
        moveOneUpPos3 = new javax.swing.JButton();
        moveOneDownPos3 = new javax.swing.JButton();
        answerPos4Panel = new javax.swing.JPanel();
        posFourText = new javax.swing.JLabel();
        buttonPanelPos4 = new javax.swing.JPanel();
        moveOneUpPos4 = new javax.swing.JButton();
        moveOneDownPos4 = new javax.swing.JButton();
        answerPos5Panel = new javax.swing.JPanel();
        posFiveText = new javax.swing.JLabel();
        buttonPanelPos5 = new javax.swing.JPanel();
        moveOneUpPos5 = new javax.swing.JButton();
        moveOneDownPos5 = new javax.swing.JButton();
        answerPos6Panel = new javax.swing.JPanel();
        posSixText = new javax.swing.JLabel();
        buttonPanelPos6 = new javax.swing.JPanel();
        moveOneUpPos6 = new javax.swing.JButton();
        moveOneDownPos6 = new javax.swing.JButton();
        answerPos7Panel = new javax.swing.JPanel();
        posSevenText = new javax.swing.JLabel();
        buttonPanelPos7 = new javax.swing.JPanel();
        moveOneUpPos7 = new javax.swing.JButton();
        moveOneDownPos7 = new javax.swing.JButton();
        answerPosBottomPanel = new javax.swing.JPanel();
        posEightText = new javax.swing.JLabel();
        buttonPanelPosEight = new javax.swing.JPanel();
        moveOneUpPos8 = new javax.swing.JButton();
        feedbackText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question UI");

        QuestionInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        QNoDisp.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        QNoDisp.setText("Question" + qNo);

        QTextDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QTextDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        MarkingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MarkingPanel.setPreferredSize(new java.awt.Dimension(76, 50));

        marksLabel.setText("Marks:");

        marksScore.setText("0/5\n");

        increaseMarkDisp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        increaseMarkDisp.setForeground(new java.awt.Color(51, 204, 0));

        totalMarksScore.setText("0/50 ");

        totalMarksLabel.setText("Total:");

        nextButton.setText("Next >>");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("<< Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(previousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout MarkingPanelLayout = new javax.swing.GroupLayout(MarkingPanel);
        MarkingPanel.setLayout(MarkingPanelLayout);
        MarkingPanelLayout.setHorizontalGroup(
            MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarkingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalMarksLabel)
                    .addComponent(marksLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marksScore)
                    .addComponent(totalMarksScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(increaseMarkDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        MarkingPanelLayout.setVerticalGroup(
            MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MarkingPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(increaseMarkDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MarkingPanelLayout.createSequentialGroup()
                        .addGroup(MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marksLabel)
                            .addComponent(marksScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(totalMarksScore, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalMarksLabel, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(15, 15, 15))
            .addGroup(MarkingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout QuestionInfoPanelLayout = new javax.swing.GroupLayout(QuestionInfoPanel);
        QuestionInfoPanel.setLayout(QuestionInfoPanelLayout);
        QuestionInfoPanelLayout.setHorizontalGroup(
            QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarkingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(QNoDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                        .addComponent(QTextDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QuestionInfoPanelLayout.setVerticalGroup(
            QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QNoDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QTextDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarkingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        QTextDisp.getAccessibleContext().setAccessibleName("Question 1:\nArrange the code snippets so that it creates an if statement that returns true if the ");

        AnswerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ButtonPanel.setPreferredSize(new java.awt.Dimension(324, 50));

        submitAnswerButton.setText("Submit Answer");
        submitAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswerButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitAnswerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(submitAnswerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        answerPosTopPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posOneText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posOneText.setText("1.");

        moveOneDownPos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos1.setText("▼");
        moveOneDownPos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout answer1TextAndButtonBlockLayout = new javax.swing.GroupLayout(answer1TextAndButtonBlock);
        answer1TextAndButtonBlock.setLayout(answer1TextAndButtonBlockLayout);
        answer1TextAndButtonBlockLayout.setHorizontalGroup(
            answer1TextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answer1TextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(moveOneDownPos1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        answer1TextAndButtonBlockLayout.setVerticalGroup(
            answer1TextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answer1TextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneDownPos1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPosTopPanelLayout = new javax.swing.GroupLayout(answerPosTopPanel);
        answerPosTopPanel.setLayout(answerPosTopPanelLayout);
        answerPosTopPanelLayout.setHorizontalGroup(
            answerPosTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPosTopPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posOneText, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer1TextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPosTopPanelLayout.setVerticalGroup(
            answerPosTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPosTopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posOneText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(answer1TextAndButtonBlock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        answerPos2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posTwoText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posTwoText.setText("2.");

        moveOneUpPos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos2.setText("▲");
        moveOneUpPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos2ActionPerformed(evt);
            }
        });

        moveOneDownPos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos2.setText("▼");
        moveOneDownPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPosTwoLayout = new javax.swing.GroupLayout(buttonPanelPosTwo);
        buttonPanelPosTwo.setLayout(buttonPanelPosTwoLayout);
        buttonPanelPosTwoLayout.setHorizontalGroup(
            buttonPanelPosTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPosTwoLayout.setVerticalGroup(
            buttonPanelPosTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPosTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos2PanelLayout = new javax.swing.GroupLayout(answerPos2Panel);
        answerPos2Panel.setLayout(answerPos2PanelLayout);
        answerPos2PanelLayout.setHorizontalGroup(
            answerPos2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos2PanelLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(posTwoText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPosTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos2PanelLayout.setVerticalGroup(
            answerPos2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posTwoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(answerPos2PanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPosTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        answerPos3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posThreeText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posThreeText.setText("3.");

        moveOneUpPos3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos3.setText("▲");
        moveOneUpPos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos3ActionPerformed(evt);
            }
        });

        moveOneDownPos3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos3.setText("▼");
        moveOneDownPos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPosThreeLayout = new javax.swing.GroupLayout(buttonPanelPosThree);
        buttonPanelPosThree.setLayout(buttonPanelPosThreeLayout);
        buttonPanelPosThreeLayout.setHorizontalGroup(
            buttonPanelPosThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPosThreeLayout.setVerticalGroup(
            buttonPanelPosThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPosThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos3PanelLayout = new javax.swing.GroupLayout(answerPos3Panel);
        answerPos3Panel.setLayout(answerPos3PanelLayout);
        answerPos3PanelLayout.setHorizontalGroup(
            answerPos3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos3PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(posThreeText, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPosThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos3PanelLayout.setVerticalGroup(
            answerPos3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos3PanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPosThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posThreeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPos4Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posFourText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posFourText.setText("4.");

        moveOneUpPos4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos4.setText("▲");
        moveOneUpPos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos4ActionPerformed(evt);
            }
        });

        moveOneDownPos4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos4.setText("▼");
        moveOneDownPos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPos4Layout = new javax.swing.GroupLayout(buttonPanelPos4);
        buttonPanelPos4.setLayout(buttonPanelPos4Layout);
        buttonPanelPos4Layout.setHorizontalGroup(
            buttonPanelPos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPos4Layout.setVerticalGroup(
            buttonPanelPos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPos4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos4PanelLayout = new javax.swing.GroupLayout(answerPos4Panel);
        answerPos4Panel.setLayout(answerPos4PanelLayout);
        answerPos4PanelLayout.setHorizontalGroup(
            answerPos4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos4PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(posFourText, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos4PanelLayout.setVerticalGroup(
            answerPos4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos4PanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPos4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos4PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posFourText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPos5Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posFiveText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posFiveText.setText("5.");

        moveOneUpPos5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos5.setText("▲");
        moveOneUpPos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos5ActionPerformed(evt);
            }
        });

        moveOneDownPos5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos5.setText("▼");
        moveOneDownPos5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPos5Layout = new javax.swing.GroupLayout(buttonPanelPos5);
        buttonPanelPos5.setLayout(buttonPanelPos5Layout);
        buttonPanelPos5Layout.setHorizontalGroup(
            buttonPanelPos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPos5Layout.setVerticalGroup(
            buttonPanelPos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPos5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos5, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos5PanelLayout = new javax.swing.GroupLayout(answerPos5Panel);
        answerPos5Panel.setLayout(answerPos5PanelLayout);
        answerPos5PanelLayout.setHorizontalGroup(
            answerPos5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos5PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(posFiveText, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos5PanelLayout.setVerticalGroup(
            answerPos5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos5PanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPos5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos5PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posFiveText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPos6Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posSixText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posSixText.setText("6.");

        moveOneUpPos6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos6.setText("▲");
        moveOneUpPos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos6ActionPerformed(evt);
            }
        });

        moveOneDownPos6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos6.setText("▼");
        moveOneDownPos6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPos6Layout = new javax.swing.GroupLayout(buttonPanelPos6);
        buttonPanelPos6.setLayout(buttonPanelPos6Layout);
        buttonPanelPos6Layout.setHorizontalGroup(
            buttonPanelPos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPos6Layout.setVerticalGroup(
            buttonPanelPos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPos6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos6, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos6PanelLayout = new javax.swing.GroupLayout(answerPos6Panel);
        answerPos6Panel.setLayout(answerPos6PanelLayout);
        answerPos6PanelLayout.setHorizontalGroup(
            answerPos6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos6PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(posSixText, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos6PanelLayout.setVerticalGroup(
            answerPos6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos6PanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPos6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos6PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posSixText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPos7Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posSevenText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posSevenText.setText("7.");

        moveOneUpPos7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos7.setText("▲");
        moveOneUpPos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos7ActionPerformed(evt);
            }
        });

        moveOneDownPos7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos7.setText("▼");
        moveOneDownPos7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPos7Layout = new javax.swing.GroupLayout(buttonPanelPos7);
        buttonPanelPos7.setLayout(buttonPanelPos7Layout);
        buttonPanelPos7Layout.setHorizontalGroup(
            buttonPanelPos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPos7Layout.setVerticalGroup(
            buttonPanelPos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPos7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPos7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos7, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos7PanelLayout = new javax.swing.GroupLayout(answerPos7Panel);
        answerPos7Panel.setLayout(answerPos7PanelLayout);
        answerPos7PanelLayout.setHorizontalGroup(
            answerPos7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos7PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(posSevenText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos7PanelLayout.setVerticalGroup(
            answerPos7PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos7PanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPos7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos7PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posSevenText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPosBottomPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        posEightText.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        posEightText.setText("false");

        moveOneUpPos8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos8.setText("▲");
        moveOneUpPos8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPosEightLayout = new javax.swing.GroupLayout(buttonPanelPosEight);
        buttonPanelPosEight.setLayout(buttonPanelPosEightLayout);
        buttonPanelPosEightLayout.setHorizontalGroup(
            buttonPanelPosEightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosEightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        buttonPanelPosEightLayout.setVerticalGroup(
            buttonPanelPosEightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosEightLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos8, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPosBottomPanelLayout = new javax.swing.GroupLayout(answerPosBottomPanel);
        answerPosBottomPanel.setLayout(answerPosBottomPanelLayout);
        answerPosBottomPanelLayout.setHorizontalGroup(
            answerPosBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPosBottomPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posEightText, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPosEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPosBottomPanelLayout.setVerticalGroup(
            answerPosBottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerPosBottomPanelLayout.createSequentialGroup()
                .addComponent(buttonPanelPosEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPosBottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posEightText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout answerBlockLayout = new javax.swing.GroupLayout(answerBlock);
        answerBlock.setLayout(answerBlockLayout);
        answerBlockLayout.setHorizontalGroup(
            answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(answerBlockLayout.createSequentialGroup()
                        .addGroup(answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(answerPos3Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answerPosBottomPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answerPosTopPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(answerPos2Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(answerPos4Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerPos5Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerPos6Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerPos7Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        answerBlockLayout.setVerticalGroup(
            answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerBlockLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(answerPosTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerPos2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answerPos3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerPos4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerPos5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerPos6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerPos7Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerPosBottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        feedbackText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        feedbackText.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout AnswerPanelLayout = new javax.swing.GroupLayout(AnswerPanel);
        AnswerPanel.setLayout(AnswerPanelLayout);
        AnswerPanelLayout.setHorizontalGroup(
            AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnswerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnswerPanelLayout.createSequentialGroup()
                        .addComponent(answerBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerPanelLayout.createSequentialGroup()
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
            .addGroup(AnswerPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(feedbackText, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
        );
        AnswerPanelLayout.setVerticalGroup(
            AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(feedbackText, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addGap(39, 39, 39)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QuestionInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AnswerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //quits to the question selection menu and save the current progress of the test, but for now just quits the application entirely
        QuestionSelect QS = new QuestionSelect(qTextArray, trueAnswers, falseAnswers, marks, completedQs, currentPoints);
        QS.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_quitButtonActionPerformed
    
    Color correctGreen = new Color(51,204,0);
    
    private void submitAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswerButtonActionPerformed
        //clear the feedback messages
        feedbackText.setText("");
        //checks the answer and provides feedback accordingly (will be the bulk of the main code for this UI eventually)
        if(isCorrect == true){
            feedbackText.setForeground(correctGreen);
            feedbackText.setText("Question Already Completed");
        }
        else{//check the current state of the randomArray against the trueArray
            if(randomAnswerArray[0].equals(trueAnswerArray[0])
            && randomAnswerArray[1].equals(trueAnswerArray[1])
            && randomAnswerArray[2].equals(trueAnswerArray[2])
            && randomAnswerArray[3].equals(trueAnswerArray[3])){
                if(currentPoints[qNo-1] == 5){
                    feedbackText.setForeground(correctGreen);
                    feedbackText.setText("√ Full marks, well done!");
                }
                else{
                    feedbackText.setForeground(correctGreen);
                    feedbackText.setText("√");
                }
                isCorrect = true;
                marksScore.setText(currentPoints + "/5");
                increaseMarkDisp.setText("+ " + currentPoints);
                //export mark list code
                marks[qNo - 1] = currentPoints[qNo-1];
                //edit the total mark list
                int markTemp = 0;
                for(int u = 0; u < 10; u++){
                    markTemp = markTemp + marks[u];
                }
                totalMarksScore.setText(markTemp + "/50");
                //label question as completed
                completedQs[qNo - 1] = true;
            }
            else if(currentPoints[qNo-1] != 0){
                feedbackText.setForeground(Color.RED);
                feedbackText.setText("<html>X <br/>1 point deducted");
                currentPoints[qNo - 1]--;
            }
            else{
                feedbackText.setForeground(Color.RED);
                feedbackText.setText("<html>X <br/> Points can no longer <br/> be earned from this <br/> question");
            }
        }
    }//GEN-LAST:event_submitAnswerButtonActionPerformed

    // Movement Buttons
    // down buttons
    private void moveOneDownPos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos1ActionPerformed
        moveTextDown(0);
    }//GEN-LAST:event_moveOneDownPos1ActionPerformed

    private void moveOneDownPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos2ActionPerformed
        moveTextDown(1);
    }//GEN-LAST:event_moveOneDownPos2ActionPerformed

    private void moveOneDownPos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos3ActionPerformed
        moveTextDown(2);
    }//GEN-LAST:event_moveOneDownPos3ActionPerformed
    
    //Up buttons
    private void moveOneUpPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos2ActionPerformed
        moveTextUp(1);
    }//GEN-LAST:event_moveOneUpPos2ActionPerformed

    private void moveOneUpPos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos3ActionPerformed
        moveTextUp(2);
    }//GEN-LAST:event_moveOneUpPos3ActionPerformed

    private void moveOneUpPos8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos8ActionPerformed
        moveTextUp(7);
    }//GEN-LAST:event_moveOneUpPos8ActionPerformed
    
    //Test navigation buttons
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        //clear the feedback messages
        feedbackText.setText("");
        if(qNo == 10){
            boolean allQsDone = false;
            for(int i = 0; i < 10; i++){
                if(completedQs[i] == true){
                    allQsDone = true;
                }
                if(completedQs[i] == false){
                    allQsDone = false;
                }
            }
            if(allQsDone == false){
                feedbackText.setForeground(Color.RED);
                feedbackText.setText("<html> Not all questions <br/> have been completed");
                
            }
            else{
                Summary Sum = new Summary(qTextArray, trueAnswers, falseAnswers, marks);
                Sum.setVisible(true);
                Sum.setDefaultCloseOperation(Sum.DO_NOTHING_ON_CLOSE);
                this.setVisible(false);
                this.dispose();
            }
        }
        else{
            ParsonsProblemsQUI QUI = new ParsonsProblemsQUI(qNo + 1, qTextArray, marks, trueAnswers, falseAnswers, completedQs, currentPoints);
            QUI.setVisible(true);
            this.setVisible(false);
            this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_nextButtonActionPerformed
    //Error shouldn't be triggered by this because the prev button should be invisible on q1
    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        ParsonsProblemsQUI QUI = new ParsonsProblemsQUI(qNo - 1, qTextArray, marks, trueAnswers, falseAnswers, completedQs, currentPoints);
        QUI.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void moveOneUpPos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos4ActionPerformed
        moveTextUp(3);
    }//GEN-LAST:event_moveOneUpPos4ActionPerformed

    private void moveOneDownPos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos4ActionPerformed
        moveTextDown(3);
    }//GEN-LAST:event_moveOneDownPos4ActionPerformed

    private void moveOneUpPos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos5ActionPerformed
        moveTextUp(4);
    }//GEN-LAST:event_moveOneUpPos5ActionPerformed

    private void moveOneDownPos5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos5ActionPerformed
        moveTextDown(4);
    }//GEN-LAST:event_moveOneDownPos5ActionPerformed

    private void moveOneUpPos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos6ActionPerformed
        moveTextUp(5);
    }//GEN-LAST:event_moveOneUpPos6ActionPerformed

    private void moveOneDownPos6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos6ActionPerformed
        moveTextDown(5);
    }//GEN-LAST:event_moveOneDownPos6ActionPerformed

    private void moveOneUpPos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos7ActionPerformed
        moveTextUp(6);
    }//GEN-LAST:event_moveOneUpPos7ActionPerformed

    private void moveOneDownPos7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos7ActionPerformed
        moveTextDown(6);
    }//GEN-LAST:event_moveOneDownPos7ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParsonsProblemsQUI(qNo, qTextArray, marks, trueAnswers, falseAnswers, completedQs, currentPoints).setVisible(true);
            }
        });
    }
    
    //used to set text fields when buttons are pressed and on window start
    private void setTextFields(){
        posOneText.setText(randomAnswerArray[0]);
        posTwoText.setText(randomAnswerArray[1]);
        posThreeText.setText(randomAnswerArray[2]);
        posFourText.setText(randomAnswerArray[3]);
        posFiveText.setText(randomAnswerArray[4]);
        posSixText.setText(randomAnswerArray[5]);
        posSevenText.setText(randomAnswerArray[6]);
        posEightText.setText(randomAnswerArray[7]);
        
        marksScore.setText(marks[qNo-1]+"/5");
    }
    
    private void initQuestionDetails(){
        QNoDisp.setText("Question " + qNo);
        QTextDisp.setText(qTextArray[qNo-1]);
    }
    
    //-----------------------------//
    //  BUTTON REARRANGEMENT CODE  //
    //-----------------------------//
        
    private void moveTextDown(int i){
        //takes the text from the inputTextField position (1. being 0, down to false being inputted as 3)
        //and shifts the text down a position, while bring the text previously there up
        String temp;
        
        temp = randomAnswerArray[i];
        randomAnswerArray[i] = randomAnswerArray[i+1];
        randomAnswerArray[i+1] = temp;
        setTextFields();
    }
    
    private void moveTextUp(int i){
        String temp;
        
        temp = randomAnswerArray[i-1];
        randomAnswerArray[i-1] = randomAnswerArray[i];
        randomAnswerArray[i] = temp;
        setTextFields();
    }
    
    //------------------------------//
    //  ANSWER RANDOMISATION CODE   //
    //------------------------------//
    
    String[] trueAnswerArray;
    String[] randomAnswerArray;
    int arrayLength = 8;                                         //
    String[] falseAnswersAlreadyInArray = new String[arrayLength - 5];
    
    private void initAnswers(){
        
        String falseAnswer1 = getRandomFalseAnswer(falseAnswers[qNo-1], falseAnswersAlreadyInArray);
        falseAnswersAlreadyInArray[0] = falseAnswer1;
        //METHOD BELOW IS A WORKAROUND FOR REQUIRING A RETURN STATEMENT IN "getRandomFalseAnswer" METHOD
        String falseAnswer2 = "INVALID";
        while(falseAnswer2 == "INVALID"){
            falseAnswer2 = getRandomFalseAnswer(falseAnswers[qNo-1], falseAnswersAlreadyInArray);
        }
        falseAnswersAlreadyInArray[1] = falseAnswer2;
        String falseAnswer3 = "INVALID";
        while(falseAnswer3 == "INVALID"){
            falseAnswer3 = getRandomFalseAnswer(falseAnswers[qNo-1], falseAnswersAlreadyInArray);
        }
        falseAnswersAlreadyInArray[2] = falseAnswer3;
        
        String falseAnswer4 = "INVALID";
        while(falseAnswer4 == "INVALID"){
            falseAnswer4 = getRandomFalseAnswer(falseAnswers[qNo-1], falseAnswersAlreadyInArray);
        }
        //the true answer array has the true order of the answer stored
        trueAnswerArray = new String[arrayLength];
        for(int i = 0; i < 3; i++){
            trueAnswerArray[i] = trueAnswers[qNo-1][i];
        }
        
        trueAnswerArray[3] = "--END OF PROGRAM--";
        trueAnswerArray[4] = falseAnswer1;
        trueAnswerArray[5] = falseAnswer2;
        trueAnswerArray[6] = falseAnswer3;
        trueAnswerArray[7] = falseAnswer4;
        
        randomAnswerArray = new String[arrayLength];
        
        randomAnswerArray = createRandomAnswerArray();
        
    }
    
    // Finds out how long the input list is, and gives a random false answer from the provided list
    /*
     * @param inAlreadyList contains the false answers already selected answers
    */
    private static String getRandomFalseAnswer(String[] inFalseAnsList, String[] inAlreadyList){
        //count the length of inFalseAnsList
        int length = inFalseAnsList.length;
        //picks a random number out of the list and put that into string and return
        int randomNumber = (int)(Math.random() * length);
        String falseAnswer = inFalseAnsList[randomNumber];
        for (int i = 0 ;i < inAlreadyList.length;i++) {
            if (falseAnswer == inAlreadyList[i]) {
                //WORKAROUND FOR REQUIRING A RETURN STATEMENT
                falseAnswer = "INVALID";
            }
        }
        return falseAnswer;
    }
    
    // This functions creates a random answer array to initially display in the text boxes
    // source for shuffling the array using collections.shuffle:  https://www.geeksforgeeks.org/collections-shuffle-java-examples/
    private String[] createRandomAnswerArray(){
        String[] randomTempArray = new String[arrayLength];
        
        // copies trueAnswerArray to the random temp array
        // since collections.shuffle does not use String[] arrays, an array list is made instead
        ArrayList<String> temp = new ArrayList<String>();
        for(int i = 0; i < trueAnswerArray.length; i++){
            temp.add(trueAnswerArray[i]);
        }
        // randomise the array, and give the random answer array all the elements
        // of the temp arrayList
        Collections.shuffle(temp);
        for(int z = 0;z < randomTempArray.length;z++){
            randomTempArray[z] = temp.get(z);
        }
        
        return randomTempArray;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnswerPanel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel MarkingPanel;
    private javax.swing.JLabel QNoDisp;
    private javax.swing.JLabel QTextDisp;
    private javax.swing.JPanel QuestionInfoPanel;
    private javax.swing.JPanel answer1TextAndButtonBlock;
    private javax.swing.JPanel answerBlock;
    private javax.swing.JPanel answerPos2Panel;
    private javax.swing.JPanel answerPos3Panel;
    private javax.swing.JPanel answerPos4Panel;
    private javax.swing.JPanel answerPos5Panel;
    private javax.swing.JPanel answerPos6Panel;
    private javax.swing.JPanel answerPos7Panel;
    private javax.swing.JPanel answerPosBottomPanel;
    private javax.swing.JPanel answerPosTopPanel;
    private javax.swing.JPanel buttonPanelPos4;
    private javax.swing.JPanel buttonPanelPos5;
    private javax.swing.JPanel buttonPanelPos6;
    private javax.swing.JPanel buttonPanelPos7;
    private javax.swing.JPanel buttonPanelPosEight;
    private javax.swing.JPanel buttonPanelPosThree;
    private javax.swing.JPanel buttonPanelPosTwo;
    private javax.swing.JLabel feedbackText;
    private javax.swing.JLabel increaseMarkDisp;
    private javax.swing.JLabel marksLabel;
    private javax.swing.JLabel marksScore;
    private javax.swing.JButton moveOneDownPos1;
    private javax.swing.JButton moveOneDownPos2;
    private javax.swing.JButton moveOneDownPos3;
    private javax.swing.JButton moveOneDownPos4;
    private javax.swing.JButton moveOneDownPos5;
    private javax.swing.JButton moveOneDownPos6;
    private javax.swing.JButton moveOneDownPos7;
    private javax.swing.JButton moveOneUpPos2;
    private javax.swing.JButton moveOneUpPos3;
    private javax.swing.JButton moveOneUpPos4;
    private javax.swing.JButton moveOneUpPos5;
    private javax.swing.JButton moveOneUpPos6;
    private javax.swing.JButton moveOneUpPos7;
    private javax.swing.JButton moveOneUpPos8;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel posEightText;
    private javax.swing.JLabel posFiveText;
    private javax.swing.JLabel posFourText;
    private javax.swing.JLabel posOneText;
    private javax.swing.JLabel posSevenText;
    private javax.swing.JLabel posSixText;
    private javax.swing.JLabel posThreeText;
    private javax.swing.JLabel posTwoText;
    private javax.swing.JButton previousButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton submitAnswerButton;
    private javax.swing.JLabel totalMarksLabel;
    private javax.swing.JLabel totalMarksScore;
    // End of variables declaration//GEN-END:variables
}
