/*
 * Are you sure dialog screen
 * Parsons Problems V0.3
 */
package parsonsproblems;

/**
 *
 * @author UP815458
 */
public class AreYouSure extends javax.swing.JFrame {
    
    static String testName;
    static String[] qTextArray;
    static String[][] trueAnswers;
    static String[][] falseAnswers;
    static int[] marks;
    static boolean[] completedQs;
    static int[] outCurrentPoints;
    
    static String descStr;
    //used for determining which screen to back to; either the question select, or the createATest
    static int mode;
    
    public AreYouSure(String inName, String[] inQTextArray, String[][] inTrueAnswers, String[][] inFalseAnswers){
        mode = 1;
        testName = inName;
        descStr = "<html>You will lose all unsaved<br>work in creating this test";
        qTextArray = inQTextArray;
        trueAnswers = inTrueAnswers;
        falseAnswers = inFalseAnswers;
        initComponents();
    }
    
    /**
     * Creates new form AreYouSure
     * @param inQTextArray
     * @param inTrueAnswers
     * @param inFalseAnswers
     * @param Qmarks
     * @param completedQuestions
     * @param inCurrentPoints
     */
    public AreYouSure(String inTestName, String[] inQTextArray, String[][] inTrueAnswers, String[][] inFalseAnswers, int [] Qmarks, boolean[] completedQuestions, int[] inCurrentPoints) {
        mode = 2;
        descStr = "<html>You will lose all<br>unsaved progress on this test";
        testName = inTestName;
        qTextArray = inQTextArray;
        trueAnswers = inTrueAnswers;
        falseAnswers = inFalseAnswers;
        initComponents();
        marks = Qmarks;
        completedQs = completedQuestions;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        desc = new javax.swing.JLabel();
        yes = new javax.swing.JButton();
        no = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Are you sure?");

        desc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        desc.setText(descStr);

        yes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        yes.setText("Yes");
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });

        no.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        no.setText("No");
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                    .addComponent(desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yes, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desc)
                .addGap(18, 18, 18)
                .addComponent(yes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        MainMenu menu = new MainMenu();
        menu.setVisible(true);
        //disable the close (x) button for the question UI
        menu.setDefaultCloseOperation(menu.DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        if(mode == 1){
            CreateATest ct = new CreateATest(testName, qTextArray, trueAnswers, falseAnswers);
            ct.setVisible(true);
            //disable the close (x) button for the question UI
            ct.setDefaultCloseOperation(ct.DO_NOTHING_ON_CLOSE);
            this.setVisible(false);
            this.dispose();
        }
        else{
            QuestionSelect QS = new QuestionSelect(testName, qTextArray, trueAnswers, falseAnswers, marks, completedQs, outCurrentPoints);
            QS.setVisible(true);
            //disable the close (x) button for the question UI
            QS.setDefaultCloseOperation(QS.DO_NOTHING_ON_CLOSE);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AreYouSure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AreYouSure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AreYouSure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AreYouSure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AreYouSure(testName, qTextArray, trueAnswers, falseAnswers, marks, completedQs, outCurrentPoints).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel desc;
    private javax.swing.JButton no;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton yes;
    // End of variables declaration//GEN-END:variables
}
