/*
 * Create A Test Save screen
 * Checks if the 
 */
package parsonsproblems;

import java.io.*;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author samgr
 */
public class CreateATestSaveScreen extends javax.swing.JFrame {
    
    static String testName;
    static String[] qTextArray;
    static String[][] trueAnswers;
    static String[][] falseAnswers;
    /**
     * Creates new form CreateATestSaveScreen
     */
    public CreateATestSaveScreen(String inName, String[] inTextArray, String[][] inTrueAnswers, String[][] inFalseAnswers) {
        initComponents();
        testName = inName;
        
        qTextArray = inTextArray;
        trueAnswers = inTrueAnswers;
        falseAnswers = inFalseAnswers;
    }
    
    private void writeFile(String inContent, String inFilename) throws IOException{
        FileWriter writer = new FileWriter("TESTDATA" + File.separator + "Tests" + File.separator + "TEST--" + inFilename);
        writer.write(inContent);
        writer.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qDescStatus = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        trueAnswerStatus = new javax.swing.JLabel();
        falseAnswerStatus = new javax.swing.JLabel();
        testNameLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qDescStatus.setText("Question Descriptions : default answers detected");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        trueAnswerStatus.setText("True Answers : default answers detected");

        falseAnswerStatus.setText("false Answers : default answers detected");

        testNameLabel.setText("Test name : testName");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Overview");

        jLabel2.setText("<html>^ these labels are non-functional<br>The quit button will take you back to change<br>the provided answers/descriptions");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(quitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(testNameLabel)
                            .addComponent(falseAnswerStatus)
                            .addComponent(trueAnswerStatus)
                            .addComponent(qDescStatus)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(testNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qDescStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueAnswerStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseAnswerStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        boolean testValid = false;
        Date date = java.util.Calendar.getInstance().getTime(); 
        String descString = "";
        for (int i = 0;i < qTextArray.length;i++) {
            descString = descString + qTextArray[i] + "\n";
        }
        String trueString = "";
        //trueAnswer string creation
        for(int i =0; i < 10;i++){
            for(int j =0; j < 3;j++){
                trueString = trueString + trueAnswers[i][j] + "\n";
            }
        }
        //false answer string creation
        String falseString = "";
        for(int i =0; i < 10;i++){
            for(int j =0; j < 6;j++){
                falseString = falseString + falseAnswers[i][j] + "\n";
            }
        }
        String fileContent = "//Test name \n" + "/Name/\n" + testName + "\n" + "//" + testName + " Test created/updated at " + date + "\n" +
                              "/d/Descriptions \n" + descString + "/t/ true answers\n" + trueString + "/f/ false answers \n" + falseString;
        try {
            writeFile(fileContent, testName);
            testValid = true;
            System.out.println("Save successful");
        } catch (IOException ex) {
            Logger.getLogger(QuestionSelect.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(testValid == true){
            MainMenu mm = new MainMenu();
            mm.setVisible(true);
            mm.setDefaultCloseOperation(mm.DO_NOTHING_ON_CLOSE);
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        CreateATest cs = new CreateATest(testName, qTextArray, trueAnswers, falseAnswers);
        cs.setVisible(true);
        cs.setDefaultCloseOperation(cs.DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_quitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateATestSaveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateATestSaveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateATestSaveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateATestSaveScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateATestSaveScreen(testName, qTextArray, trueAnswers, falseAnswers).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel falseAnswerStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel qDescStatus;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel testNameLabel;
    private javax.swing.JLabel trueAnswerStatus;
    // End of variables declaration//GEN-END:variables
}
