/*
 * Create a Test
 */
package parsonsproblems;

/**
 * @author UP815458
 */
public class CreateATest extends javax.swing.JFrame {
    
    static String testName;
    static String[] qTextArray;
    static String[][] trueAnswers;
    static String[][] falseAnswers;
    
    int currentQuestion = 0;
    
    //INT BELOW ONLY TO BE EDITED WHEN EXPANDING/SHRINKING NUMBER OF QUESTIONS IN A TEST
    int NO_OF_QUESTIONS = 10;

    /**
     * Creates new form CreateATest
     * Parameter-less constructor used on selection of "create a new test", creates a new test from scratch
     */
    public CreateATest() {
        initComponents();
        testName = "untitled";
        qTextArray = new String[10];
        trueAnswers = new String[10][3];
        falseAnswers = new String[10][6];
        initDefaultTestValues();
        feedbackText.setText("");
        setTextFields();
    }
    
    //Constructor with parameters used when returning from the are you sure menu or when loading a previous test file
        
    public CreateATest(String inName, String [] inQText, String[][] inTrueAnswers, String[][] inFalseAnswers){
        //TESTNAME
        testName = inName;
        //DESCRIPTIONS
        qTextArray = inQText;
        //TRUE
        trueAnswers = inTrueAnswers;
        //FALSE
        falseAnswers = inFalseAnswers;
        //Set feedback to blank
        feedbackText.setText("");
        setTextFields();
    }

    private void setTextFields(){
        //TEXTNAME
        testTitleTextField.setText(testName);
        //DESCRIPTIONS
        qDescTextField.setText(qTextArray[currentQuestion]);
        //TRUE
        trueCode0.setText(trueAnswers[currentQuestion][0]);
        trueCode1.setText(trueAnswers[currentQuestion][1]);
        trueCode2.setText(trueAnswers[currentQuestion][2]);
        //FALSE
        falseCode0.setText(falseAnswers[currentQuestion][0]);
        falseCode1.setText(falseAnswers[currentQuestion][1]);
        falseCode2.setText(falseAnswers[currentQuestion][2]);
        falseCode3.setText(falseAnswers[currentQuestion][3]);
        falseCode4.setText(falseAnswers[currentQuestion][4]);
        falseCode5.setText(falseAnswers[currentQuestion][5]);
    }
    
    private void initDefaultTestValues(){
        for(int i = 0; i < NO_OF_QUESTIONS; i++){
            qTextArray[i] = "<html>default Description: enter some new text here";
        }
        for(int i = 0; i < NO_OF_QUESTIONS; i++){
            for(int j = 0; j < 3; j++){
                trueAnswers[i][j] = "True code snippet " + (j+1) +"/3";
            }
        }
        for(int i = 0; i < NO_OF_QUESTIONS; i++){
            for(int j = 0; j < 6; j++){
                falseAnswers[i][j] = "False code snippet " + (j+1) +"/6";
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionInfoPanel = new javax.swing.JPanel();
        testTitleLabel = new javax.swing.JLabel();
        testTitleTextField = new javax.swing.JTextField();
        qTextInstructions = new javax.swing.JLabel();
        qDescTextField = new javax.swing.JTextField();
        feedbackText = new javax.swing.JLabel();
        changeQuestionPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        marksScore = new javax.swing.JLabel();
        answerPanel = new javax.swing.JPanel();
        trueCode0 = new javax.swing.JTextField();
        trueCode1 = new javax.swing.JTextField();
        trueCode2 = new javax.swing.JTextField();
        endOfProgramLabel = new javax.swing.JLabel();
        falseCode0 = new javax.swing.JTextField();
        falseCode1 = new javax.swing.JTextField();
        falseCode2 = new javax.swing.JTextField();
        falseCode3 = new javax.swing.JTextField();
        falseCode4 = new javax.swing.JTextField();
        falseCode5 = new javax.swing.JTextField();
        quitButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        QuestionInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        testTitleLabel.setText("Test name : ");

        qTextInstructions.setText("Edit question 1's description text below:");

        qDescTextField.setText("Description Text Field");

        feedbackText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        feedbackText.setForeground(new java.awt.Color(255, 0, 51));
        feedbackText.setText("Feedback appears here");

        changeQuestionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        changeQuestionPanel.setPreferredSize(new java.awt.Dimension(76, 50));

        nextButton.setText("Next >>");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        previousButton.setText("<< Previous");
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });

        marksScore.setText("Question 1/10");

        javax.swing.GroupLayout changeQuestionPanelLayout = new javax.swing.GroupLayout(changeQuestionPanel);
        changeQuestionPanel.setLayout(changeQuestionPanelLayout);
        changeQuestionPanelLayout.setHorizontalGroup(
            changeQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeQuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marksScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(previousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        changeQuestionPanelLayout.setVerticalGroup(
            changeQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeQuestionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(marksScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(changeQuestionPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(changeQuestionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nextButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(previousButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout QuestionInfoPanelLayout = new javax.swing.GroupLayout(QuestionInfoPanel);
        QuestionInfoPanel.setLayout(QuestionInfoPanelLayout);
        QuestionInfoPanelLayout.setHorizontalGroup(
            QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeQuestionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                        .addGroup(QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(feedbackText, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                                .addComponent(qTextInstructions)
                                .addComponent(qDescTextField))
                            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                                .addComponent(testTitleLabel)
                                .addGap(13, 13, 13)
                                .addComponent(testTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        QuestionInfoPanelLayout.setVerticalGroup(
            QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testTitleTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testTitleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qTextInstructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qDescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(feedbackText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(changeQuestionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        answerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        trueCode0.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        trueCode0.setText("True code snippet 1/3");

        trueCode1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        trueCode1.setText("True code snippet 2/3");

        trueCode2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        trueCode2.setText("True code snippet 3/3");

        endOfProgramLabel.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        endOfProgramLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        endOfProgramLabel.setText("-- END OF PROGRAM --");

        falseCode0.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        falseCode0.setText("False code snippet 1/6");

        falseCode1.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        falseCode1.setText("False code snippet 2/6");

        falseCode2.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        falseCode2.setText("False code snippet 3/6");

        falseCode3.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        falseCode3.setText("False code snippet 4/6");

        falseCode4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        falseCode4.setText("False code snippet 5/6");

        falseCode5.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        falseCode5.setText("False code snippet 6/6");

        javax.swing.GroupLayout answerPanelLayout = new javax.swing.GroupLayout(answerPanel);
        answerPanel.setLayout(answerPanelLayout);
        answerPanelLayout.setHorizontalGroup(
            answerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(answerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trueCode2)
                    .addComponent(trueCode1)
                    .addComponent(trueCode0)
                    .addComponent(endOfProgramLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(falseCode0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(falseCode1)
                    .addComponent(falseCode2)
                    .addComponent(falseCode3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(falseCode4)
                    .addComponent(falseCode5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        answerPanelLayout.setVerticalGroup(
            answerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(trueCode0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trueCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endOfProgramLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseCode0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseCode2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseCode3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(falseCode5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Finish & Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuestionInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(answerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quitButton)
                        .addGap(450, 450, 450)
                        .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuestionInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quitButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Previous/next buttons
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        //Clear the feedback message
        feedbackText.setText("");
        if(currentQuestion == 9){
            feedbackText.setText("There are no more questions");
        } else {
            //TESTNAME
            testName = testTitleTextField.getText();
            //DESCRIPTION
            qTextArray[currentQuestion] = qDescTextField.getText();
            //TRUE
            trueAnswers[currentQuestion][0] = trueCode0.getText();
            trueAnswers[currentQuestion][1] = trueCode1.getText();
            trueAnswers[currentQuestion][2] = trueCode2.getText();
            //FALSE
            falseAnswers[currentQuestion][0] = falseCode0.getText();
            falseAnswers[currentQuestion][1] = falseCode1.getText();
            falseAnswers[currentQuestion][2] = falseCode2.getText();
            falseAnswers[currentQuestion][3] = falseCode3.getText();
            falseAnswers[currentQuestion][4] = falseCode4.getText();
            falseAnswers[currentQuestion][5] = falseCode5.getText();
            //increase question number and set new values in the text fields
            currentQuestion++;
            setTextFields();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        //Clear the feedback message
        feedbackText.setText("");
        if(currentQuestion == 0){
            feedbackText.setText("");
        } else {
            //TESTNAME
            testName = testTitleTextField.getText();
            //DESCRIPTION
            qTextArray[currentQuestion] = qDescTextField.getText();
            //TRUE
            trueAnswers[currentQuestion][0] = trueCode0.getText();
            trueAnswers[currentQuestion][1] = trueCode1.getText();
            trueAnswers[currentQuestion][2] = trueCode2.getText();
            //FALSE
            falseAnswers[currentQuestion][0] = falseCode0.getText();
            falseAnswers[currentQuestion][1] = falseCode1.getText();
            falseAnswers[currentQuestion][2] = falseCode2.getText();
            falseAnswers[currentQuestion][3] = falseCode3.getText();
            falseAnswers[currentQuestion][4] = falseCode4.getText();
            falseAnswers[currentQuestion][5] = falseCode5.getText();
            //decrease question number and set new values in the text fields
            currentQuestion--;
            setTextFields();
        }
    }//GEN-LAST:event_previousButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        AreYouSure ys = new AreYouSure(testName, qTextArray, trueAnswers, falseAnswers);
        ys.setVisible(true);
        ys.setDefaultCloseOperation(ys.DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_quitButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        //
        //TESTNAME
        testName = testTitleTextField.getText();
        //DESCRIPTION
        qTextArray[currentQuestion] = qDescTextField.getText();
        //TRUE
        trueAnswers[currentQuestion][0] = trueCode0.getText();
        trueAnswers[currentQuestion][1] = trueCode1.getText();
        trueAnswers[currentQuestion][2] = trueCode2.getText();
        //FALSE
        falseAnswers[currentQuestion][0] = falseCode0.getText();
        falseAnswers[currentQuestion][1] = falseCode1.getText();
        falseAnswers[currentQuestion][2] = falseCode2.getText();
        falseAnswers[currentQuestion][3] = falseCode3.getText();
        falseAnswers[currentQuestion][4] = falseCode4.getText();
        falseAnswers[currentQuestion][5] = falseCode5.getText();
        
        CreateATestSaveScreen cts = new CreateATestSaveScreen(testName, qTextArray, trueAnswers, falseAnswers);
        cts.setVisible(true);
        cts.setDefaultCloseOperation(cts.DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateATest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateATest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateATest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateATest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateATest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuestionInfoPanel;
    private javax.swing.JPanel answerPanel;
    private javax.swing.JPanel changeQuestionPanel;
    private javax.swing.JLabel endOfProgramLabel;
    private javax.swing.JTextField falseCode0;
    private javax.swing.JTextField falseCode1;
    private javax.swing.JTextField falseCode2;
    private javax.swing.JTextField falseCode3;
    private javax.swing.JTextField falseCode4;
    private javax.swing.JTextField falseCode5;
    private javax.swing.JLabel feedbackText;
    private javax.swing.JLabel marksScore;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    private javax.swing.JTextField qDescTextField;
    private javax.swing.JLabel qTextInstructions;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel testTitleLabel;
    private javax.swing.JTextField testTitleTextField;
    private javax.swing.JTextField trueCode0;
    private javax.swing.JTextField trueCode1;
    private javax.swing.JTextField trueCode2;
    // End of variables declaration//GEN-END:variables
}
