/*
 * Parsons Problems Question UI V0.2
 * the Question UI now acts completely independently, taking in
 */
package parsonsproblems;

import java.util.ArrayList;
import java.util.Collections;


/**
 * @author UP815458
 */
public class ParsonsProblemsQUI extends javax.swing.JFrame {
    
    /**
     * Initialises the components and sets up the question
     * @param qNo the question number to be displayed
     */
    public ParsonsProblemsQUI(int qNumber, String qTxt, int[] inMarks, String[] trueAnswerList, String[] falseAnswerList, boolean[] completedQuestions) {
        qNo = qNumber;
        qText = qTxt;
        marks = inMarks;
        trueAnswers = trueAnswerList;
        falseAnswers = falseAnswerList;
        completedQs = completedQuestions;
        System.out.println("Initialising question answers\n...");
        initAnswers();
        System.out.println("...\nQuestion answers Initialized");
        initComponents();
        initQuestionDetails();
        setTextFields();
        System.out.println("Question UI Initialized");
    }
    
    static int qNo;
    static String qText;
    static String[] trueAnswers;
    static String[] falseAnswers;
    static int[] marks;
    static boolean[] completedQs;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuestionInfoPanel = new javax.swing.JPanel();
        QNoDisp = new javax.swing.JLabel();
        QTextDisp = new javax.swing.JLabel();
        MarkingPanel = new javax.swing.JPanel();
        marksLabel = new javax.swing.JLabel();
        marksScore = new javax.swing.JLabel();
        increaseMarkDisp = new javax.swing.JLabel();
        AnswerPanel = new javax.swing.JPanel();
        ButtonPanel = new javax.swing.JPanel();
        quitButton = new javax.swing.JButton();
        submitAnswerButton = new javax.swing.JButton();
        answerBlock = new javax.swing.JPanel();
        answerPos1Panel = new javax.swing.JPanel();
        PosOneLabel = new javax.swing.JLabel();
        answer1TextAndButtonBlock = new javax.swing.JPanel();
        posOneTextField = new javax.swing.JTextField();
        moveOneDownPos1 = new javax.swing.JButton();
        answerPos2Panel = new javax.swing.JPanel();
        PosTwoLabel = new javax.swing.JLabel();
        answerTwoTextAndButtonBlock = new javax.swing.JPanel();
        posTwoTextField = new javax.swing.JTextField();
        buttonPanelPosTwo = new javax.swing.JPanel();
        moveOneUpPos2 = new javax.swing.JButton();
        moveOneDownPos2 = new javax.swing.JButton();
        answerPos3Panel = new javax.swing.JPanel();
        PosThreeLabel = new javax.swing.JLabel();
        answerThreeTextAndButtonBlock = new javax.swing.JPanel();
        posThreeTextField = new javax.swing.JTextField();
        buttonPanelPosThree = new javax.swing.JPanel();
        moveOneUpPos3 = new javax.swing.JButton();
        moveOneDownPos3 = new javax.swing.JButton();
        answerPosFalsePanel = new javax.swing.JPanel();
        PosFalseLabel = new javax.swing.JLabel();
        answerFalseTextAndButtonBlock = new javax.swing.JPanel();
        posFalseTextField = new javax.swing.JTextField();
        buttonPanelPosFalse = new javax.swing.JPanel();
        moveOneUpPos4 = new javax.swing.JButton();
        redFeedbackText = new javax.swing.JLabel();
        greenFeedbackText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question UI");

        QuestionInfoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        QNoDisp.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        QNoDisp.setText("Question" + qNo);

        QTextDisp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        QTextDisp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        QTextDisp.setText(qText);

        MarkingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MarkingPanel.setPreferredSize(new java.awt.Dimension(76, 50));

        marksLabel.setText("Marks:");

        marksScore.setText("0/5\n");

        increaseMarkDisp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        increaseMarkDisp.setForeground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout MarkingPanelLayout = new javax.swing.GroupLayout(MarkingPanel);
        MarkingPanel.setLayout(MarkingPanelLayout);
        MarkingPanelLayout.setHorizontalGroup(
            MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarkingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(marksLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marksScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(increaseMarkDisp)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MarkingPanelLayout.setVerticalGroup(
            MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MarkingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MarkingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(increaseMarkDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marksLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(marksScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout QuestionInfoPanelLayout = new javax.swing.GroupLayout(QuestionInfoPanel);
        QuestionInfoPanel.setLayout(QuestionInfoPanelLayout);
        QuestionInfoPanelLayout.setHorizontalGroup(
            QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QNoDisp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QTextDisp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MarkingPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addContainerGap())
        );
        QuestionInfoPanelLayout.setVerticalGroup(
            QuestionInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuestionInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QNoDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QTextDisp, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MarkingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        QTextDisp.getAccessibleContext().setAccessibleName("Question 1:\nArrange the code snippets so that it creates an if statement that returns true if the ");

        AnswerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ButtonPanel.setPreferredSize(new java.awt.Dimension(324, 50));

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        submitAnswerButton.setText("Submit Answer");
        submitAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAnswerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submitAnswerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitButton)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton)
                    .addComponent(submitAnswerButton))
                .addContainerGap())
        );

        answerPos1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PosOneLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PosOneLabel.setText("1.");

        posOneTextField.setEditable(false);

        moveOneDownPos1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos1.setText("▼");
        moveOneDownPos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout answer1TextAndButtonBlockLayout = new javax.swing.GroupLayout(answer1TextAndButtonBlock);
        answer1TextAndButtonBlock.setLayout(answer1TextAndButtonBlockLayout);
        answer1TextAndButtonBlockLayout.setHorizontalGroup(
            answer1TextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answer1TextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posOneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(moveOneDownPos1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        answer1TextAndButtonBlockLayout.setVerticalGroup(
            answer1TextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answer1TextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(answer1TextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(posOneTextField))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerPos1PanelLayout = new javax.swing.GroupLayout(answerPos1Panel);
        answerPos1Panel.setLayout(answerPos1PanelLayout);
        answerPos1PanelLayout.setHorizontalGroup(
            answerPos1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PosOneLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer1TextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos1PanelLayout.setVerticalGroup(
            answerPos1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PosOneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(answer1TextAndButtonBlock, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        answerPos2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PosTwoLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PosTwoLabel.setText("2.");

        posTwoTextField.setEditable(false);

        moveOneUpPos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos2.setText("▲");
        moveOneUpPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos2ActionPerformed(evt);
            }
        });

        moveOneDownPos2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos2.setText("▼");
        moveOneDownPos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPosTwoLayout = new javax.swing.GroupLayout(buttonPanelPosTwo);
        buttonPanelPosTwo.setLayout(buttonPanelPosTwoLayout);
        buttonPanelPosTwoLayout.setHorizontalGroup(
            buttonPanelPosTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPosTwoLayout.setVerticalGroup(
            buttonPanelPosTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPosTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerTwoTextAndButtonBlockLayout = new javax.swing.GroupLayout(answerTwoTextAndButtonBlock);
        answerTwoTextAndButtonBlock.setLayout(answerTwoTextAndButtonBlockLayout);
        answerTwoTextAndButtonBlockLayout.setHorizontalGroup(
            answerTwoTextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerTwoTextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanelPosTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        answerTwoTextAndButtonBlockLayout.setVerticalGroup(
            answerTwoTextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerTwoTextAndButtonBlockLayout.createSequentialGroup()
                .addComponent(buttonPanelPosTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerTwoTextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posTwoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout answerPos2PanelLayout = new javax.swing.GroupLayout(answerPos2Panel);
        answerPos2Panel.setLayout(answerPos2PanelLayout);
        answerPos2PanelLayout.setHorizontalGroup(
            answerPos2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos2PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PosTwoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerTwoTextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        answerPos2PanelLayout.setVerticalGroup(
            answerPos2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerPos2PanelLayout.createSequentialGroup()
                .addComponent(answerTwoTextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PosTwoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPos3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PosThreeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PosThreeLabel.setText("3.");

        posThreeTextField.setEditable(false);

        moveOneUpPos3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos3.setText("▲");
        moveOneUpPos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos3ActionPerformed(evt);
            }
        });

        moveOneDownPos3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneDownPos3.setText("▼");
        moveOneDownPos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneDownPos3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPosThreeLayout = new javax.swing.GroupLayout(buttonPanelPosThree);
        buttonPanelPosThree.setLayout(buttonPanelPosThreeLayout);
        buttonPanelPosThreeLayout.setHorizontalGroup(
            buttonPanelPosThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveOneDownPos3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        buttonPanelPosThreeLayout.setVerticalGroup(
            buttonPanelPosThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonPanelPosThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(moveOneDownPos3, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(moveOneUpPos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout answerThreeTextAndButtonBlockLayout = new javax.swing.GroupLayout(answerThreeTextAndButtonBlock);
        answerThreeTextAndButtonBlock.setLayout(answerThreeTextAndButtonBlockLayout);
        answerThreeTextAndButtonBlockLayout.setHorizontalGroup(
            answerThreeTextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerThreeTextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPanelPosThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        answerThreeTextAndButtonBlockLayout.setVerticalGroup(
            answerThreeTextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerThreeTextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posThreeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(answerThreeTextAndButtonBlockLayout.createSequentialGroup()
                .addComponent(buttonPanelPosThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout answerPos3PanelLayout = new javax.swing.GroupLayout(answerPos3Panel);
        answerPos3Panel.setLayout(answerPos3PanelLayout);
        answerPos3PanelLayout.setHorizontalGroup(
            answerPos3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPos3PanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(PosThreeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerThreeTextAndButtonBlock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        answerPos3PanelLayout.setVerticalGroup(
            answerPos3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerPos3PanelLayout.createSequentialGroup()
                .addComponent(answerThreeTextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPos3PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PosThreeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        answerPosFalsePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        PosFalseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PosFalseLabel.setText("<html>False<br/>answer");

        posFalseTextField.setEditable(false);

        moveOneUpPos4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moveOneUpPos4.setText("▲");
        moveOneUpPos4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveOneUpPos4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelPosFalseLayout = new javax.swing.GroupLayout(buttonPanelPosFalse);
        buttonPanelPosFalse.setLayout(buttonPanelPosFalseLayout);
        buttonPanelPosFalseLayout.setHorizontalGroup(
            buttonPanelPosFalseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosFalseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        buttonPanelPosFalseLayout.setVerticalGroup(
            buttonPanelPosFalseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelPosFalseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moveOneUpPos4, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout answerFalseTextAndButtonBlockLayout = new javax.swing.GroupLayout(answerFalseTextAndButtonBlock);
        answerFalseTextAndButtonBlock.setLayout(answerFalseTextAndButtonBlockLayout);
        answerFalseTextAndButtonBlockLayout.setHorizontalGroup(
            answerFalseTextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerFalseTextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(posFalseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPanelPosFalse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        answerFalseTextAndButtonBlockLayout.setVerticalGroup(
            answerFalseTextAndButtonBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerFalseTextAndButtonBlockLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(posFalseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(answerFalseTextAndButtonBlockLayout.createSequentialGroup()
                .addComponent(buttonPanelPosFalse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout answerPosFalsePanelLayout = new javax.swing.GroupLayout(answerPosFalsePanel);
        answerPosFalsePanel.setLayout(answerPosFalsePanelLayout);
        answerPosFalsePanelLayout.setHorizontalGroup(
            answerPosFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerPosFalsePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PosFalseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answerFalseTextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        answerPosFalsePanelLayout.setVerticalGroup(
            answerPosFalsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, answerPosFalsePanelLayout.createSequentialGroup()
                .addComponent(answerFalseTextAndButtonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(answerPosFalsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PosFalseLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout answerBlockLayout = new javax.swing.GroupLayout(answerBlock);
        answerBlock.setLayout(answerBlockLayout);
        answerBlockLayout.setHorizontalGroup(
            answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerBlockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(answerPos3Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerPosFalsePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(answerPos1Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(answerPos2Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        answerBlockLayout.setVerticalGroup(
            answerBlockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(answerBlockLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(answerPos1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerPos2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerPos3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answerPosFalsePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        redFeedbackText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        redFeedbackText.setForeground(new java.awt.Color(255, 0, 51));

        greenFeedbackText.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        greenFeedbackText.setForeground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout AnswerPanelLayout = new javax.swing.GroupLayout(AnswerPanel);
        AnswerPanel.setLayout(AnswerPanelLayout);
        AnswerPanelLayout.setHorizontalGroup(
            AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnswerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnswerPanelLayout.createSequentialGroup()
                        .addComponent(answerBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerPanelLayout.createSequentialGroup()
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
            .addGroup(AnswerPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(greenFeedbackText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(redFeedbackText)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        AnswerPanelLayout.setVerticalGroup(
            AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(answerBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(AnswerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AnswerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(redFeedbackText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(greenFeedbackText, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(QuestionInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AnswerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(QuestionInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        //quits to the question selection menu and save the current progress of the test, but for now just quits the application entirely
        QuestionSelect QS = new QuestionSelect(marks, completedQs);
        QS.setVisible(true);
        this.setVisible(false);
        this.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_quitButtonActionPerformed

    boolean isCorrect = false;
    int currentPoints = 5;
    private void submitAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAnswerButtonActionPerformed
        //clear the feedback messages
        greenFeedbackText.setText("");
        redFeedbackText.setText("");
        //checks the answer and provides feedback accordingly (will be the bulk of the main code for this UI eventually)
        if(isCorrect == true){
            greenFeedbackText.setText("√, Marks Already earned");
        }
        else{//check the current state of the randomArray against the trueArray
            if(randomAnswerArray[0].equals(trueAnswerArray[0])
            && randomAnswerArray[1].equals(trueAnswerArray[1])
            && randomAnswerArray[2].equals(trueAnswerArray[2])
            && randomAnswerArray[3].equals(trueAnswerArray[3])  ){
                if(currentPoints == 5){
                    greenFeedbackText.setText("√ Full marks, well done!");
                }
                else{
                    greenFeedbackText.setText("√");
                }
                isCorrect = true;
                marksScore.setText(currentPoints + "/5");
                increaseMarkDisp.setText("+ " + currentPoints);
                
                //export mark list code
                marks[qNo - 1] = currentPoints;
                //label question as completed
                completedQs[qNo - 1] = true;
            }
            else if(currentPoints != 0){
                redFeedbackText.setText("<html>X <br/>1 point deducted");
                if(currentPoints != 0){
                    currentPoints--;
                }
            }
            else{
                redFeedbackText.setText("<html>X <br/> Points can no longer <br/> be earned from this <br/> question");
            }
        }
    }//GEN-LAST:event_submitAnswerButtonActionPerformed

    // Movement Buttons
    // down buttons
    private void moveOneDownPos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos1ActionPerformed
        moveTextDown(0);
    }//GEN-LAST:event_moveOneDownPos1ActionPerformed

    private void moveOneDownPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos2ActionPerformed
        moveTextDown(1);
    }//GEN-LAST:event_moveOneDownPos2ActionPerformed

    private void moveOneDownPos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneDownPos3ActionPerformed
        moveTextDown(2);
    }//GEN-LAST:event_moveOneDownPos3ActionPerformed
    
    //Up buttons
    private void moveOneUpPos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos2ActionPerformed
        moveTextUp(1);
    }//GEN-LAST:event_moveOneUpPos2ActionPerformed

    private void moveOneUpPos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos3ActionPerformed
        moveTextUp(2);
    }//GEN-LAST:event_moveOneUpPos3ActionPerformed

    private void moveOneUpPos4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveOneUpPos4ActionPerformed
        moveTextUp(3);
    }//GEN-LAST:event_moveOneUpPos4ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParsonsProblemsQUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParsonsProblemsQUI(qNo, qText, marks, trueAnswers, falseAnswers, completedQs).setVisible(true);
            }
        });
    }
    
    //used to set text fields when buttons are pressed and on window start
    private void setTextFields(){
        posOneTextField.setText(randomAnswerArray[0]);
        posTwoTextField.setText(randomAnswerArray[1]);
        posThreeTextField.setText(randomAnswerArray[2]);
        posFalseTextField.setText(randomAnswerArray[3]);
    }
    
    private void initQuestionDetails(){
        QNoDisp.setText("Question " + qNo);
    }
    
    //-----------------------------//
    //  BUTTON REARRANGEMENT CODE  //
    //-----------------------------//
        
    private void moveTextDown(int i){
        //takes the text from the inputTextField position (1. being 0, down to false being inputted as 3)
        //and shifts the text down a position, while bring the text previously there up
        String temp;
        
        temp = randomAnswerArray[i];
        randomAnswerArray[i] = randomAnswerArray[i+1];
        randomAnswerArray[i+1] = temp;
        setTextFields();
    }
    
    private void moveTextUp(int i){
        String temp;
        
        temp = randomAnswerArray[i-1];
        randomAnswerArray[i-1] = randomAnswerArray[i];
        randomAnswerArray[i] = temp;
        setTextFields();
    }
    
    //------------------------------//
    //  ANSWER RANDOMISATION CODE   //
    //------------------------------//
    
    String[] trueAnswerArray;
    String[] randomAnswerArray;
    
    private void initAnswers(){
        String falseAnswer = getRandomFalseAnswer(falseAnswers);
        //the true answer array has the true order of the answer stored
        trueAnswerArray = new String[4];
        for(int i = 0; i < trueAnswerArray.length - 1; i++){
            trueAnswerArray[i] = trueAnswers[i];
        }
        
        trueAnswerArray[3] = falseAnswer;
        randomAnswerArray = new String[4];
        
        randomAnswerArray = createRandomAnswerArray();
        
    }
    
    // Finds out how long the input list is, and gives a random false answer from the provided list
    private static String getRandomFalseAnswer(String[] inFalseAnsList){
        //count the length of inFalseAnsList
        int length = inFalseAnsList.length;
        //picks a random number out of the list and put that into string and return
        int randomNumber = (int)(Math.random() * length);
        
        String falseAnswer = inFalseAnsList[randomNumber];
        return falseAnswer;
    }
    
    // This functions creates a random answer array to initially display in the text boxes
    // source for shuffling the array using collections.shuffle:  https://www.geeksforgeeks.org/collections-shuffle-java-examples/
    private String[] createRandomAnswerArray(){
        String[] randomTempArray = new String[4];
        
        // copies trueAnswerArray to the random temp array
        // since collections.shuffle does not use String[] arrays, an array list is made instead
        ArrayList<String> temp = new ArrayList<String>();
        for(int i = 0; i < trueAnswerArray.length; i++){
            temp.add(trueAnswerArray[i]);
        }
        // randomise the array, and give the random answer array all the elements
        // of the temp arrayList
        Collections.shuffle(temp);
        for(int z = 0;z < randomTempArray.length;z++){
            randomTempArray[z] = temp.get(z);
        }
        
        return randomTempArray;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnswerPanel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel MarkingPanel;
    private javax.swing.JLabel PosFalseLabel;
    private javax.swing.JLabel PosOneLabel;
    private javax.swing.JLabel PosThreeLabel;
    private javax.swing.JLabel PosTwoLabel;
    private javax.swing.JLabel QNoDisp;
    private javax.swing.JLabel QTextDisp;
    private javax.swing.JPanel QuestionInfoPanel;
    private javax.swing.JPanel answer1TextAndButtonBlock;
    private javax.swing.JPanel answerBlock;
    private javax.swing.JPanel answerFalseTextAndButtonBlock;
    private javax.swing.JPanel answerPos1Panel;
    private javax.swing.JPanel answerPos2Panel;
    private javax.swing.JPanel answerPos3Panel;
    private javax.swing.JPanel answerPosFalsePanel;
    private javax.swing.JPanel answerThreeTextAndButtonBlock;
    private javax.swing.JPanel answerTwoTextAndButtonBlock;
    private javax.swing.JPanel buttonPanelPosFalse;
    private javax.swing.JPanel buttonPanelPosThree;
    private javax.swing.JPanel buttonPanelPosTwo;
    private javax.swing.JLabel greenFeedbackText;
    private javax.swing.JLabel increaseMarkDisp;
    private javax.swing.JLabel marksLabel;
    private javax.swing.JLabel marksScore;
    private javax.swing.JButton moveOneDownPos1;
    private javax.swing.JButton moveOneDownPos2;
    private javax.swing.JButton moveOneDownPos3;
    private javax.swing.JButton moveOneUpPos2;
    private javax.swing.JButton moveOneUpPos3;
    private javax.swing.JButton moveOneUpPos4;
    private javax.swing.JTextField posFalseTextField;
    private javax.swing.JTextField posOneTextField;
    private javax.swing.JTextField posThreeTextField;
    private javax.swing.JTextField posTwoTextField;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel redFeedbackText;
    private javax.swing.JButton submitAnswerButton;
    // End of variables declaration//GEN-END:variables
}
